import { createHmac } from "crypto";

// PEAK accounting API client — https://developers.peakaccount.com (API Core v1).
// Goal: auto-post a guide payout as a PEAK expense and read back its document
// number (the EXP-… ref) into PayrollStatus.peakRef.
//
// Credentials live ONLY in Railway env vars (never in code / git):
//   PEAK_CONNECT_ID, PEAK_CONNECT_KEY  developer creds from PEAK (sign + client token)
//   PEAK_USER_TOKEN                    generated by the business owner in PEAK after
//                                      consenting to connect this app (static)
//   PEAK_API_BASE_URL / PEAK_BASE_URL  API root (either var; API_BASE_URL wins).
//                                      Defaults to the UAT sandbox; set prod URL to go live
//
// Auth: HMAC-SHA1 sign a timestamp -> POST /ClientToken -> use Client-Token +
// User-Token headers on every call. Two doc ambiguities (which value is the HMAC
// secret, and the digest encoding) are env-overridable so we can match the sandbox
// on first contact without a redeploy. Nothing runs until the env is set.

// Base URL: Railway carries both PEAK_API_BASE_URL and PEAK_BASE_URL. Prefer the
// API-specific one, fall back to the original var (what this client shipped with),
// then the UAT sandbox. Either may be given as the host root or already suffixed
// with /api/v1 — normalizePeakBase() makes both resolve to the same API root, so
// the env can be set either way without a code change.
export function normalizePeakBase(raw?: string | null): string {
  const base = (raw || "https://peakengineapidev.azurewebsites.net").trim().replace(/\/+$/, "");
  return /\/api\/v\d+$/i.test(base) ? base : `${base}/api/v1`;
}

const API = normalizePeakBase(process.env.PEAK_API_BASE_URL || process.env.PEAK_BASE_URL);
// Trimmed on read, like the base URL above. A credential pasted into Railway with a
// trailing newline or a stray space is non-empty — so peakConfigured goes green — but
// signs a wrong HMAC and sends a wrong connectId, which reads as "credentials rejected"
// with no way to tell it apart from a genuinely bad key. Trimming also makes a
// whitespace-only value report as missing (red dot) instead of silently failing.
const CONNECT_ID = (process.env.PEAK_CONNECT_ID || "").trim();
const CONNECT_KEY = (process.env.PEAK_CONNECT_KEY || "").trim();
const USER_TOKEN = (process.env.PEAK_USER_TOKEN || "").trim();
const SIGN_SECRET = (process.env.PEAK_SIGN_SECRET || "connectId") === "connectKey" ? CONNECT_KEY : CONNECT_ID;
// Verified against the PEAK UAT sandbox: the Time-Signature is HMAC-SHA1(connectId,
// timestamp) hex-encoded. Overridable, but hex is the working default (base64 →
// "TimeSignature Unauthorized").
const SIG_ENC: "hex" | "base64" = process.env.PEAK_SIG_ENCODING === "base64" ? "base64" : "hex";

export const peakConfigured = !!(CONNECT_ID && CONNECT_KEY);
export const peakEnabled = !!(CONNECT_ID && CONNECT_KEY && USER_TOKEN);
export const peakBaseUrl = API;

// yyyyMMdd HHmmss in UTC — PEAK validates the timestamp against its own (UTC)
// clock, so a Bangkok +7h stamp is rejected as out-of-window ("Invalid API
// Validate Data. (TimeStamp)"). Exported (pure) so it can be unit-tested.
export function peakTimestamp(d: Date = new Date()): string {
  const p = (n: number) => String(n).padStart(2, "0");
  return `${d.getUTCFullYear()}${p(d.getUTCMonth() + 1)}${p(d.getUTCDate())}${p(d.getUTCHours())}${p(d.getUTCMinutes())}${p(d.getUTCSeconds())}`;
}

// Which required env vars are missing (NAMES only — never values). Used by the
// connection test so a misconfigured deploy says what to set, not what it holds.
export function peakMissingEnv(): string[] {
  return [
    ["PEAK_CONNECT_ID", CONNECT_ID],
    ["PEAK_CONNECT_KEY", CONNECT_KEY],
  ].filter(([, v]) => !v).map(([k]) => k as string);
}

// Last line of defence before any PEAK text reaches a log or an HTTP response:
// strip anything that matches a credential or a token we hold. PEAK's own
// resCode/resDesc never contain secrets, but this guarantees it.
export function sanitizePeakError(msg: unknown): string {
  let out = typeof msg === "string" ? msg : msg instanceof Error ? msg.message : "unknown error";
  for (const secret of [CONNECT_ID, CONNECT_KEY, USER_TOKEN, cached?.token]) {
    if (secret && secret.length >= 6) out = out.split(secret).join("[redacted]");
  }
  return out.slice(0, 300);
}

function stamp(): string {
  return peakTimestamp();
}

// PEAK responses capitalize the wrapper key (e.g. `PeakClientToken`) while requests
// send it lowercase — read either casing so a valid response is never missed.
function peakWrap<T>(j: Record<string, unknown>, key: string): T | undefined {
  const cap = key.charAt(0).toUpperCase() + key.slice(1);
  return (j[key] ?? j[cap]) as T | undefined;
}

/** Which spelling of the wrapper key the response actually used, or null. */
function peakWrapName(j: Record<string, unknown>, key: string): string | null {
  const cap = key.charAt(0).toUpperCase() + key.slice(1);
  if (j && Object.prototype.hasOwnProperty.call(j, key)) return key;
  if (j && Object.prototype.hasOwnProperty.call(j, cap)) return cap;
  return null;
}

/**
 * What a PEAK reply actually was, in terms safe to show an operator: shape and
 * status, never contents. Every read path returns one of these so a diagnostic
 * can say why a list came back empty instead of just reporting zero.
 */
export type PeakEnvelope = {
  httpStatus: number;
  wrapperName: string | null;   // the key PEAK used, e.g. "PeakAccountCode"
  wrapperKeys: string[];        // FIELD NAMES inside the wrapper — never values
  resCode: string | null;
  resDesc: string | null;       // sanitized
  arrayKey: string | null;      // which wrapper field held the rows
  rawCount: number | null;      // rows before any filtering
};

/**
 * Whether PEAK's own code reports a failure.
 *
 * PEAK answers application errors with HTTP 200, so the transport status alone
 * cannot decide this. What it does NOT do is publish the success code anywhere
 * we can verify: "0000" appears in one test fixture in this repo and in no
 * documentation we hold, and the ClientToken path has always decided success by
 * looking for a token rather than a code.
 *
 * So the rule is deliberately conservative in one direction: an all-zero or
 * absent code is success, anything else is an error. It is only ever consulted
 * when the reply carried NO data — a response with rows in it is a success
 * whatever the code says, because inventing a stricter rule could turn a working
 * integration into a broken one on a code we have never seen.
 */
export function peakCodeIsError(code: unknown): boolean {
  const c = (code == null ? "" : String(code)).trim();
  if (!c) return false;          // absent — nothing is being reported
  if (/^0+$/.test(c)) return false; // "0", "0000" — success in every PEAK reply seen
  return true;
}

/** Read the envelope without interpreting the payload. */
export function readPeakEnvelope(
  j: Record<string, unknown>,
  wrapperKey: string,
  httpStatus: number,
): { envelope: PeakEnvelope; wrap: Record<string, unknown> | undefined } {
  const wrap = peakWrap<Record<string, unknown>>(j ?? {}, wrapperKey);
  const wrapperKeys = wrap && typeof wrap === "object" ? Object.keys(wrap) : [];
  const arrays = wrapperKeys.filter((k) => Array.isArray(wrap?.[k]));
  const arrayKey = arrays.find((k) => /account|code|chart|method|contact|list|item|data|row/i.test(k)) ?? arrays[0] ?? null;
  const rows = arrayKey ? (wrap?.[arrayKey] as unknown[]) : null;
  const rawDesc = wrap?.resDesc;
  return {
    wrap,
    envelope: {
      httpStatus,
      wrapperName: peakWrapName(j ?? {}, wrapperKey),
      wrapperKeys: wrapperKeys.slice(0, 16),
      resCode: wrap?.resCode == null ? null : String(wrap.resCode),
      resDesc: rawDesc == null ? null : sanitizePeakError(rawDesc),
      arrayKey,
      rawCount: Array.isArray(rows) ? rows.length : null,
    },
  };
}

/**
 * The shared failure decision for every read call.
 *
 * Fails on a non-2xx, and on a 200 whose PEAK code reports an error while the
 * body carried nothing usable — which is the case that used to be reported as a
 * successful empty list.
 */
export function peakReadFailure(
  envelope: PeakEnvelope,
  httpOk: boolean,
  hasData: boolean,
): { code?: string; desc: string } | null {
  if (!httpOk) {
    return { code: envelope.resCode ?? undefined, desc: envelope.resDesc || `HTTP ${envelope.httpStatus}` };
  }
  if (hasData) return null; // rows arrived — that is a success whatever the code says
  if (peakCodeIsError(envelope.resCode)) {
    return {
      code: envelope.resCode ?? undefined,
      desc: envelope.resDesc || `PEAK returned HTTP 200 with error code ${envelope.resCode}`,
    };
  }
  return null;
}
function sigHeaders(): Record<string, string> {
  const ts = stamp();
  const sig = createHmac("sha1", SIGN_SECRET).update(ts).digest(SIG_ENC);
  return { "Time-Stamp": ts, "Time-Signature": sig };
}

// PEAK's documented list paging. 200 is what this client has always asked for;
// 500 is the ceiling it will accept before rejecting the request.
export const PEAK_LIST_LIMIT = 200;
export const PEAK_MAX_LIST_LIMIT = 500;

type Res<T> = { ok: boolean; code?: string; desc?: string } & T;

let cached: { token: string; at: number } | null = null;

// Nothing here used to time out. A PEAK call that never answers left the request
// open indefinitely, and the Job Sheet then sat on "Loading PEAK contacts…" —
// the exact same screen as the bug where the request was never sent at all
// (#185). An unbounded wait that looks identical to a missing request is not a
// failure anyone can diagnose, so every call now has a deadline and says so.
const READ_TIMEOUT_MS = 15_000;
const TOKEN_TIMEOUT_MS = 10_000;
// A write waits longer before giving up, because abandoning it early is what
// creates the "did the document get created?" question.
const WRITE_TIMEOUT_MS = 30_000;

// AbortSignal.timeout rejects with a TimeoutError; say that plainly instead of
// reporting it as a generic network fault.
export function callFailure(e: unknown, ms: number): string {
  const err = e as { name?: string; message?: string };
  if (err?.name === "TimeoutError" || err?.name === "AbortError") {
    return `PEAK did not respond within ${Math.round(ms / 1000)}s`;
  }
  return sanitizePeakError(`network: ${err?.message ?? String(e)}`);
}

// One ClientToken attempt. PEAK's docs name the secret field `password`; this
// client shipped sending `connectKey`, which commit 076b3c0 proved the UAT
// sandbox accepts. Both carry the same PEAK_CONNECT_KEY value, so we try the
// documented name first and fall back to the proven one rather than guessing.
async function requestClientToken(field: "password" | "connectKey"): Promise<Res<{ token?: string }>> {
  let r: Response;
  try {
    r = await fetch(`${API}/ClientToken`, {
      method: "POST",
      headers: { "content-type": "application/json", ...sigHeaders() },
      body: JSON.stringify({ peakClientToken: { connectId: CONNECT_ID, [field]: CONNECT_KEY } }),
      signal: AbortSignal.timeout(TOKEN_TIMEOUT_MS),
    });
  } catch (e) { return { ok: false, desc: callFailure(e, TOKEN_TIMEOUT_MS) }; }
  const j = await r.json().catch(() => ({} as Record<string, unknown>));
  const t = peakWrap<{ token?: string; resCode?: string; resDesc?: string }>(j, "peakClientToken");
  if (t?.token) return { ok: true, token: t.token, code: t.resCode, desc: t.resDesc };
  // Non-2xx, or a 200 carrying PEAK's own error code: surface the code/description
  // only — never the raw body (it echoes the request) and never the credentials.
  return { ok: false, code: t?.resCode, desc: sanitizePeakError(t?.resDesc || `HTTP ${r.status}`) };
}

export async function clientToken(force = false): Promise<Res<{ token?: string }>> {
  const missing = peakMissingEnv();
  if (missing.length) return { ok: false, desc: `not configured: set ${missing.join(", ")}` };
  if (!force && cached && Date.now() - cached.at < 50 * 60_000) return { ok: true, token: cached.token };
  let res = await requestClientToken("password");
  if (!res.ok) res = await requestClientToken("connectKey");
  if (res.ok && res.token) cached = { token: res.token, at: Date.now() };
  return res;
}

/**
 * Does this reply say PEAK rejected our client token?
 *
 * The token is cached for 50 minutes, and nothing used to notice when PEAK stopped
 * accepting it: every real call then failed with "Invalid Client Token" until the
 * cache aged out, while "Test connection" kept passing because it forces a fresh
 * one. The account-chart page showed exactly that — green credentials, a working
 * payment-method list, and an unavailable account list, all at once.
 */
export function clientTokenRejected(httpStatus: number, resCode?: string | null, resDesc?: string | null): boolean {
  if (httpStatus === 401) return true;
  const d = `${resDesc ?? ""} ${resCode ?? ""}`.toLowerCase();
  if (!d.includes("token")) return false;
  return d.includes("invalid") || d.includes("expire") || d.includes("unauthor");
}

/**
 * One authenticated call: build headers, send, parse the body.
 *
 * `retry` (default on) sends the call a SECOND time with a freshly minted token when
 * the first reply says the token was rejected — that is the whole fix for a stale
 * cache, and it is safe for a read.
 *
 * `fresh` mints a new token before the FIRST attempt. Writes use this instead of the
 * retry: replaying a write after a failure risks a second document if the first one
 * reached PEAK and only the reply was lost, whereas one extra handshake beforehand
 * costs nothing and removes the stale-token failure outright.
 */
async function authedCall(
  url: string,
  init: RequestInit,
  wrapperKey: string,
  opts: { fresh?: boolean; retry?: boolean; timeoutMs?: number } = {},
): Promise<{ r: Response; j: Record<string, unknown> } | { error: string }> {
  const attempt = async (fresh: boolean): Promise<{ r: Response; j: Record<string, unknown> } | { error: string }> => {
    const ct = await clientToken(fresh);
    if (!ct.ok || !ct.token) return { error: ct.desc ? sanitizePeakError(ct.desc) : "could not obtain PEAK client token" };
    const headers = { "content-type": "application/json", "Client-Token": ct.token, "User-Token": USER_TOKEN, ...sigHeaders() };
    const ms = opts.timeoutMs ?? READ_TIMEOUT_MS;
    try {
      const r = await fetch(url, { ...init, headers, signal: AbortSignal.timeout(ms) });
      return { r, j: await r.json().catch(() => ({} as Record<string, unknown>)) };
    } catch (e) {
      return { error: callFailure(e, ms) };
    }
  };

  const first = await attempt(!!opts.fresh);
  if ("error" in first || opts.retry === false) return first;
  const { envelope } = readPeakEnvelope(first.j, wrapperKey, first.r.status);
  if (!clientTokenRejected(first.r.status, envelope.resCode, envelope.resDesc)) return first;
  // The cached token is dead. Drop it so the next caller does not inherit it either.
  cached = null;
  return attempt(true);
}

// One combined expense + payment (peakExpenses.expenses[] shape). Returns the
// created document `code` (the EXP-… reference).
export async function createExpenseAllInOne(expense: Record<string, unknown>): Promise<Res<{ id?: string; link?: string }>> {
  if (!peakEnabled) return { ok: false, desc: "PEAK not fully configured (need PEAK_USER_TOKEN)" };
  // A write gets a fresh token up front and is never replayed — see authedCall.
  const call = await authedCall(
    `${API}/Expenses/allinone`,
    { method: "POST", body: JSON.stringify({ peakExpenses: { expenses: [expense], getResult: 1 } }) },
    "peakExpenses",
    { fresh: true, retry: false, timeoutMs: WRITE_TIMEOUT_MS },
  );
  // A write that timed out may still have reached PEAK. Say so, because the next
  // step is to look in PEAK before reposting — not to press the button again.
  if ("error" in call) {
    return { ok: false, desc: call.error.includes("did not respond")
      ? `${call.error}. The expense may or may not have been created — check PEAK before posting this job sheet again.`
      : call.error };
  }
  const { r, j } = call;
  const wrap = peakWrap<{ expenses?: Array<{ code?: string; id?: string; documentLink?: string; resCode?: string; resDesc?: string }>; resDesc?: string }>(j, "peakExpenses");
  const e = wrap?.expenses?.[0];
  if (e?.code) return { ok: true, code: e.code, id: e.id, link: e.documentLink, desc: e.resDesc };
  return { ok: false, code: e?.resCode, desc: e?.resDesc || wrap?.resDesc || `HTTP ${r.status}` };
}

// Identity of the connected PEAK account (read-only).
// GET /api/v1/User/detail, wrapper PeakUser. This is the only way to answer "whose
// books are we actually looking at" — the merchant name and tax number say whether
// the credentials belong to Folkpaths or to a sandbox demo company.
//
// Returns SAFE fields only. The response also carries the user's personal name,
// email and address; none of that is needed to identify an environment, so none of
// it is passed on.
export type PeakIdentity = { merchantName: string; taxNumber: string | null; package: string | null; branchCode: string | null };

export async function getUserDetail(): Promise<Res<{ identity?: PeakIdentity; envelope?: PeakEnvelope }>> {
  if (!peakEnabled) return { ok: false, desc: "PEAK not fully configured (need PEAK_USER_TOKEN)" };
  const call = await authedCall(`${API}/User/detail`, { method: "GET" }, "peakUser");
  if ("error" in call) return { ok: false, desc: call.error };
  const { r, j } = call;
  const { envelope, wrap } = readPeakEnvelope(j, "peakUser", r.status);
  // Identity carries no array; "data" here means a merchant name came back.
  const hasData = Boolean(wrap && typeof wrap === "object" && String(wrap.name ?? "").trim());
  const failure = peakReadFailure(envelope, r.ok, hasData);
  if (failure) return { ok: false, code: failure.code, desc: failure.desc, envelope };
  if (!wrap || typeof wrap !== "object") {
    return { ok: false, envelope, desc: `PEAK replied ${r.status} but no user detail was found. Response keys: [${Object.keys(j ?? {}).slice(0, 8).join(", ") || "none"}]` };
  }
  const str = (v: unknown) => (v == null ? null : String(v).trim() || null);
  return {
    ok: true,
    identity: {
      merchantName: str(wrap.name) ?? "",
      taxNumber: str(wrap.taxNumber),
      package: str(wrap.package),
      branchCode: str(wrap.branchCode),
    },
    code: envelope.resCode ?? undefined,
    desc: envelope.resDesc ?? undefined,
    envelope,
  };
}

// Chart of accounts (read-only) — the account code + name list an operator picks
// from when mapping FolkOPS categories. GET /api/v1/DailyJournals/accountcode per
// PEAK's API reference; response wrapper is PeakAccountCode -> accountCode[].
//
// Deliberately READ-ONLY: this cannot create or post anything. It reuses the same
// authedCall()/peakWrap()/sanitizePeakError() path as getContacts() below, so
// the Client Token handshake is untouched.
export type PeakAccountCode = { code: string; name: string; nameEn?: string };

// Pure parser for the chart response, exported so the shape can be unit tested —
// this call has never run against PEAK, so the parsing is the part most likely to
// be wrong and the part hardest to verify live.
//
// Returns either the accounts, or a diagnostic naming the KEYS actually present
// (never their values — the payload is business data). A 200 whose shape we
// misread would otherwise look like a working call with no accounts, which is the
// worst outcome because it is silent.
export type AccountParse =
  | { accounts: PeakAccountCode[]; meta: { wrapperKeys: string[]; arrayKey: string; rawCount: number; droppedNoCode: number; sampleKeys: string[] } }
  | { error: string };

export function parsePeakAccounts(j: Record<string, unknown>): AccountParse {
  const wrap = peakWrap<Record<string, unknown>>(j ?? {}, "peakAccountCode");
  const wrapperKeys = wrap && typeof wrap === "object" ? Object.keys(wrap) : [];
  const arrays = wrapperKeys.filter((k) => Array.isArray((wrap as Record<string, unknown>)[k]));
  const arrayKey = arrays.find((k) => /account|code|chart/i.test(k)) ?? arrays[0];

  if (!arrayKey) {
    const topKeys = Object.keys(j ?? {}).slice(0, 8);
    return {
      error: `PEAK replied 200 but no account array was found. Response keys: [${topKeys.join(", ") || "none"}]` +
             (wrapperKeys.length ? `; inside the wrapper: [${wrapperKeys.slice(0, 8).join(", ")}]` : ""),
    };
  }

  const raw = ((wrap as Record<string, unknown>)[arrayKey] ?? []) as PeakAccountCode[];
  // The FIELD NAMES of the first entry. This is the diagnostic that matters when
  // the array has rows but none survive: if PEAK calls the code something other
  // than `code`, every row is filtered out and the list looks empty. Names only —
  // the chart of accounts is business data.
  const sampleKeys = raw.length && raw[0] && typeof raw[0] === "object" ? Object.keys(raw[0]).slice(0, 12) : [];

  const accounts = raw
    .filter((a) => (a?.code ?? "").toString().trim())
    .map((a) => ({ code: String(a.code).trim(), name: String(a.name ?? "").trim(), nameEn: a.nameEn ? String(a.nameEn).trim() : undefined }));

  return { accounts, meta: { wrapperKeys, arrayKey, rawCount: raw.length, droppedNoCode: raw.length - accounts.length, sampleKeys } };
}

export async function getAccountCodes(): Promise<Res<{ accounts?: PeakAccountCode[]; envelope?: PeakEnvelope; meta?: { wrapperKeys: string[]; arrayKey: string; rawCount: number; droppedNoCode: number; sampleKeys: string[] } }>> {
  if (!peakEnabled) return { ok: false, desc: "PEAK not fully configured (need PEAK_USER_TOKEN)" };
  // No query string. PEAK's paging parameters are documented for the list
  // endpoints below; this path is NOT confirmed against the current Production
  // API (see the note above), so adding parameters it may not accept would only
  // add a second reason for it to fail.
  const call = await authedCall(`${API}/DailyJournals/accountcode`, { method: "GET" }, "peakAccountCode");
  if ("error" in call) return { ok: false, desc: call.error };
  const { r, j } = call;
  const { envelope } = readPeakEnvelope(j, "peakAccountCode", r.status);
  const parsed = parsePeakAccounts(j);
  const hasData = !("error" in parsed) && parsed.meta.rawCount > 0;
  const failure = peakReadFailure(envelope, r.ok, hasData);
  if (failure) return { ok: false, code: failure.code, desc: failure.desc, envelope };
  if ("error" in parsed) return { ok: false, code: envelope.resCode ?? undefined, desc: sanitizePeakError(envelope.resDesc || parsed.error), envelope };
  return { ok: true, accounts: parsed.accounts, meta: parsed.meta, code: envelope.resCode ?? undefined, desc: envelope.resDesc ?? undefined, envelope };
}

// Payment methods (read-only) — the bank/cash accounts a payment can settle to.
// GET /api/v1/PaymentMethods, wrapper PeakPaymentMethods. PEAK's docs list the
// object's fields but not the array key inside the wrapper, so the parser accepts
// the documented naming pattern and REPORTS what it found when it cannot match —
// the same defence added after the chart call shipped unverified.
export type PeakPaymentMethod = { id: string; code?: string; name: string; type?: string; bankName?: string; accountNumber?: string };

export type PaymentMethodParse =
  | { methods: PeakPaymentMethod[]; meta: { wrapperKeys: string[]; arrayKey: string; rawCount: number; droppedNoId: number; sampleKeys: string[] } }
  | { error: string };

export function parsePeakPaymentMethods(j: Record<string, unknown>): PaymentMethodParse {
  const wrap = peakWrap<Record<string, unknown>>(j ?? {}, "peakPaymentMethods");
  const wrapperKeys = wrap && typeof wrap === "object" ? Object.keys(wrap) : [];

  // Prefer an array whose key actually names payment methods; only then fall back
  // to "the first array present". Picking the first array blindly could latch onto
  // an unrelated collection and quietly return the wrong list.
  const arrays = wrapperKeys.filter((k) => Array.isArray((wrap as Record<string, unknown>)[k]));
  const arrayKey = arrays.find((k) => /payment|method|bank|account/i.test(k)) ?? arrays[0];

  if (!arrayKey) {
    const topKeys = Object.keys(j ?? {}).slice(0, 8);
    return {
      error: `PEAK replied 200 but no payment-method array was found. Response keys: [${topKeys.join(", ") || "none"}]` +
             (wrapperKeys.length ? `; inside the wrapper: [${wrapperKeys.slice(0, 8).join(", ")}]` : ""),
    };
  }

  const raw = ((wrap as Record<string, unknown>)[arrayKey] ?? []) as PeakPaymentMethod[];
  const methods = raw
    .filter((m) => (m?.id ?? "").toString().trim())
    .map((m) => ({
      id: String(m.id).trim(),
      code: m.code ? String(m.code).trim() : undefined,
      name: String(m.name ?? "").trim(),
      type: m.type ? String(m.type).trim() : undefined,
      bankName: m.bankName ? String(m.bankName).trim() : undefined,
      accountNumber: m.accountNumber ? String(m.accountNumber).trim() : undefined,
    }));

  // rawCount vs methods.length is the whole point: it separates "PEAK only has one
  // payment method" from "we silently dropped the others". Without it, a short list
  // is indistinguishable from a parsing bug.
  const sampleKeys = raw.length && raw[0] && typeof raw[0] === "object" ? Object.keys(raw[0]).slice(0, 12) : [];
  return { methods, meta: { wrapperKeys, arrayKey, rawCount: raw.length, droppedNoId: raw.length - methods.length, sampleKeys } };
}

export async function getPaymentMethods(): Promise<Res<{ methods?: PeakPaymentMethod[]; envelope?: PeakEnvelope; meta?: { wrapperKeys: string[]; arrayKey: string; rawCount: number; droppedNoId: number; sampleKeys: string[] } }>> {
  if (!peakEnabled) return { ok: false, desc: "PEAK not fully configured (need PEAK_USER_TOKEN)" };

  // PEAK pages at 10 entries per page by default and this call sent no params at
  // all, so a company with more than ten payment methods would silently see only
  // the first page. Ask for the lot.
  // page + limit are the documented list parameters. getResult is NOT sent: in
  // PEAK's reference it belongs to the write endpoints (it asks for the created
  // document back), and this client only uses it on Expenses/allinone. Sending it
  // to a GET would be guessing.
  const pmQs = new URLSearchParams({ page: "1", limit: String(PEAK_LIST_LIMIT) });
  const call = await authedCall(`${API}/PaymentMethods?${pmQs.toString()}`, { method: "GET" }, "peakPaymentMethods");
  if ("error" in call) return { ok: false, desc: call.error };
  const { r, j } = call;
  const { envelope } = readPeakEnvelope(j, "peakPaymentMethods", r.status);
  const parsed = parsePeakPaymentMethods(j);
  const hasData = !("error" in parsed) && parsed.meta.rawCount > 0;
  const failure = peakReadFailure(envelope, r.ok, hasData);
  if (failure) return { ok: false, code: failure.code, desc: failure.desc, envelope };
  if ("error" in parsed) return { ok: false, code: envelope.resCode ?? undefined, desc: sanitizePeakError(envelope.resDesc || parsed.error), envelope };
  return { ok: true, methods: parsed.methods, meta: parsed.meta, code: envelope.resCode ?? undefined, desc: envelope.resDesc ?? undefined, envelope };
}

// Vendor/contact list (read-only) — the guides that already exist in PEAK, so an
// operator LINKS to one instead of pasting an opaque id.
// GET /api/v1/Contacts/list, wrapper PeakContacts -> contacts[].
//
// PEAK pages at 10 entries by default, so `limit` is always sent: a picker that
// silently showed the first ten guides would look like the rest do not exist.
export type PeakContact = { id: string; name: string; code?: string; taxNumber?: string; type?: string };

export function parsePeakContacts(j: Record<string, unknown>): { contacts: PeakContact[] } | { error: string } {
  const wrap = peakWrap<{ contacts?: unknown; resCode?: string; resDesc?: string }>(j ?? {}, "peakContacts");
  const list = wrap?.contacts;
  if (!Array.isArray(list)) {
    const topKeys = Object.keys(j ?? {}).slice(0, 8);
    const innerKeys = wrap && typeof wrap === "object" ? Object.keys(wrap).slice(0, 8) : [];
    return {
      error: `PEAK replied 200 but no contact array was found. Response keys: [${topKeys.join(", ") || "none"}]` +
             (innerKeys.length ? `; inside the wrapper: [${innerKeys.join(", ")}]` : ""),
    };
  }
  const contacts = (list as PeakContact[])
    .filter((c) => (c?.id ?? "").toString().trim())
    .map((c) => ({
      id: String(c.id).trim(),
      name: String(c.name ?? "").trim(),
      code: c.code ? String(c.code).trim() : undefined,
      taxNumber: c.taxNumber ? String(c.taxNumber).trim() : undefined,
      type: c.type != null ? String(c.type).trim() : undefined,
    }));
  return { contacts };
}

export async function getContacts(opts: { searchText?: string; limit?: number; page?: number } = {}): Promise<Res<{ contacts?: PeakContact[]; envelope?: PeakEnvelope }>> {
  if (!peakEnabled) return { ok: false, desc: "PEAK not fully configured (need PEAK_USER_TOKEN)" };
  const qs = new URLSearchParams();
  if (opts.searchText?.trim()) qs.set("searchText", opts.searchText.trim());
  qs.set("limit", String(Math.min(Math.max(opts.limit ?? PEAK_LIST_LIMIT, 1), PEAK_MAX_LIST_LIMIT)));
  // Always paged: an omitted page has meant "page 1" in every reply seen, but
  // saying so makes the request reproducible when a count looks wrong.
  qs.set("page", String(Math.max(opts.page ?? 1, 1)));
  const call = await authedCall(`${API}/Contacts/list?${qs.toString()}`, { method: "GET" }, "peakContacts");
  if ("error" in call) return { ok: false, desc: call.error };
  const { r, j } = call;
  const { envelope } = readPeakEnvelope(j, "peakContacts", r.status);
  const parsed = parsePeakContacts(j);
  const hasData = !("error" in parsed) && parsed.contacts.length > 0;
  const failure = peakReadFailure(envelope, r.ok, hasData);
  if (failure) return { ok: false, code: failure.code, desc: failure.desc, envelope };
  if ("error" in parsed) return { ok: false, code: envelope.resCode ?? undefined, desc: sanitizePeakError(envelope.resDesc || parsed.error), envelope };
  return { ok: true, contacts: parsed.contacts, code: envelope.resCode ?? undefined, desc: envelope.resDesc ?? undefined, envelope };
}
