import { createHmac } from "crypto";

// PEAK accounting API client — https://developers.peakaccount.com (API Core v1).
// Goal: auto-post a guide payout as a PEAK expense and read back its document
// number (the EXP-… ref) into PayrollStatus.peakRef.
//
// Credentials live ONLY in Railway env vars (never in code / git):
//   PEAK_CONNECT_ID, PEAK_CONNECT_KEY  developer creds from PEAK (sign + client token)
//   PEAK_USER_TOKEN                    generated by the business owner in PEAK after
//                                      consenting to connect this app (static)
//   PEAK_BASE_URL                      defaults to the UAT sandbox; set prod URL to go live
//
// Auth: HMAC-SHA1 sign a timestamp -> POST /ClientToken -> use Client-Token +
// User-Token headers on every call. Two doc ambiguities (which value is the HMAC
// secret, and the digest encoding) are env-overridable so we can match the sandbox
// on first contact without a redeploy. Nothing runs until the env is set.

const BASE = (process.env.PEAK_BASE_URL || "https://peakengineapidev.azurewebsites.net").replace(/\/+$/, "");
const CONNECT_ID = process.env.PEAK_CONNECT_ID || "";
const CONNECT_KEY = process.env.PEAK_CONNECT_KEY || "";
const USER_TOKEN = process.env.PEAK_USER_TOKEN || "";
const SIGN_SECRET = (process.env.PEAK_SIGN_SECRET || "connectId") === "connectKey" ? CONNECT_KEY : CONNECT_ID;
const SIG_ENC: "hex" | "base64" = process.env.PEAK_SIG_ENCODING === "hex" ? "hex" : "base64";

export const peakConfigured = !!(CONNECT_ID && CONNECT_KEY);
export const peakEnabled = !!(CONNECT_ID && CONNECT_KEY && USER_TOKEN);
export const peakBaseUrl = BASE;

function stamp(): string {
  const d = new Date(Date.now() + 7 * 3600 * 1000); // Bangkok wall-clock
  const p = (n: number) => String(n).padStart(2, "0");
  return `${d.getUTCFullYear()}${p(d.getUTCMonth() + 1)}${p(d.getUTCDate())}${p(d.getUTCHours())}${p(d.getUTCMinutes())}${p(d.getUTCSeconds())}`;
}
function sigHeaders(): Record<string, string> {
  const ts = stamp();
  const sig = createHmac("sha1", SIGN_SECRET).update(ts).digest(SIG_ENC);
  return { "Time-Stamp": ts, "Time-Signature": sig };
}

type Res<T> = { ok: boolean; code?: string; desc?: string } & T;

let cached: { token: string; at: number } | null = null;
export async function clientToken(force = false): Promise<Res<{ token?: string }>> {
  if (!peakConfigured) return { ok: false, desc: "PEAK_CONNECT_ID / PEAK_CONNECT_KEY not set" };
  if (!force && cached && Date.now() - cached.at < 50 * 60_000) return { ok: true, token: cached.token };
  let r: Response;
  try {
    r = await fetch(`${BASE}/api/v1/ClientToken`, {
      method: "POST",
      headers: { "content-type": "application/json", ...sigHeaders() },
      body: JSON.stringify({ peakClientToken: { connectId: CONNECT_ID, connectKey: CONNECT_KEY } }),
    });
  } catch (e) { return { ok: false, desc: `network: ${(e as Error).message}` }; }
  const j = await r.json().catch(() => ({} as Record<string, unknown>));
  const t = (j as { peakClientToken?: { token?: string; resCode?: string; resDesc?: string } }).peakClientToken;
  if (t?.token) { cached = { token: t.token, at: Date.now() }; return { ok: true, token: t.token, code: t.resCode, desc: t.resDesc }; }
  return { ok: false, code: t?.resCode, desc: t?.resDesc || `HTTP ${r.status}` };
}

async function authedHeaders(): Promise<Record<string, string> | null> {
  const ct = await clientToken();
  if (!ct.ok || !ct.token) return null;
  return { "content-type": "application/json", "Client-Token": ct.token, "User-Token": USER_TOKEN, ...sigHeaders() };
}

// One combined expense + payment (peakExpenses.expenses[] shape). Returns the
// created document `code` (the EXP-… reference).
export async function createExpenseAllInOne(expense: Record<string, unknown>): Promise<Res<{ id?: string; link?: string }>> {
  if (!peakEnabled) return { ok: false, desc: "PEAK not fully configured (need PEAK_USER_TOKEN)" };
  const headers = await authedHeaders();
  if (!headers) return { ok: false, desc: "could not obtain PEAK client token" };
  let r: Response;
  try {
    r = await fetch(`${BASE}/api/v1/Expenses/allinone`, { method: "POST", headers, body: JSON.stringify({ peakExpenses: { expenses: [expense], getResult: 1 } }) });
  } catch (e) { return { ok: false, desc: `network: ${(e as Error).message}` }; }
  const j = await r.json().catch(() => ({} as Record<string, unknown>));
  const wrap = (j as { peakExpenses?: { expenses?: Array<{ code?: string; id?: string; documentLink?: string; resCode?: string; resDesc?: string }>; resDesc?: string } }).peakExpenses;
  const e = wrap?.expenses?.[0];
  if (e?.code) return { ok: true, code: e.code, id: e.id, link: e.documentLink, desc: e.resDesc };
  return { ok: false, code: e?.resCode, desc: e?.resDesc || wrap?.resDesc || `HTTP ${r.status}` };
}

// Vendor/contact list — used to map a guide -> a PEAK contact id.
export async function getContacts(): Promise<Res<{ contacts?: unknown[] }>> {
  if (!peakEnabled) return { ok: false, desc: "PEAK not fully configured (need PEAK_USER_TOKEN)" };
  const headers = await authedHeaders();
  if (!headers) return { ok: false, desc: "could not obtain PEAK client token" };
  let r: Response;
  try { r = await fetch(`${BASE}/api/v1/Contacts/list`, { method: "GET", headers }); }
  catch (e) { return { ok: false, desc: `network: ${(e as Error).message}` }; }
  const j = await r.json().catch(() => ({} as Record<string, unknown>));
  const wrap = (j as { peakContacts?: { contacts?: unknown[]; resCode?: string; resDesc?: string } }).peakContacts;
  return { ok: r.ok, contacts: wrap?.contacts, code: wrap?.resCode, desc: wrap?.resDesc };
}
